### ISSUE TITLE
`set-output` deprecation warning

### ISSUE THREAD

**Issue by baynezy** [thomaseizinger/keep-a-changelog-new-release#29]
I get the following after every run of your action.

```bash
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ for more information.

From my understanding, you need to [move to set the release notes via `setOutput()` to the environment variable  `GITHUB_OUTPUT`](https://github.com/thomaseizinger/keep-a-changelog-new-release/blob/master/src/index.ts#L28C5-L28C46).

I think this bug was introduced with https://github.com/thomaseizinger/keep-a-changelog-new-release/pull/28

**Comment by thomaseizinger** [comment]
We just use the SDK function. Maybe we need a dependency update? PRs welcome!

**Comment by baynezy** [comment]
I am pretty sure that all you need to do is update `@actions/core`. I have tried this, but I am no Typescript developer and I just get hammered by a web of yarn and jest issues. This is likely due to my not knowing what I am doing in this ecosystem. By changing one version number in the `package.json` file it changed hundreds of lines of the `yarn.lock` file.

Now when I run the tests `getInputs.test.ts` complains that `Cannot find module 'node:stream' from 'main.js'`. There is no `main.js` in your project. So I am at an impass.

I hope that someone else who cares about this project and does have familiarity with Typescript; can make this hopefully simple change.

**Comment by thomaseizinger** [comment]
Thank you for trying! npm is an absolute mess and I don't have the bandwidth to deal with it right now unfortunately.

Is there an EOL deadline for when we need to deal with this warning?

**Comment by baynezy** [comment]
@thomaseizinger they've been trying to remove that functionality since mid last year. They keep postponing it because not enough people have moved. However, it's only a matter of time.

**Comment by baynezy** [comment]
@nbusseneau - I am not sure if this is something you could pick up. It was introduced in your PR #28

**Comment by nbusseneau** [comment]
No, sorry. I am not dealing with any of this mess, I already lost enough of my sanity in just getting it to work for #28, as you can see from looking at the thread.

**Comment by nbusseneau** [comment]
(And yes, updating the `@actions/core` dependency will suffice here, the action has been supporting the new file-command objects ever since that initial deprecation notice, no additional code change should be needed, though getting the project to update as a whole probably will.)
